# Generated by Django 3.2 on 2022-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(default='placeholder', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
