# Generated by Django 3.2 on 2022-06-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bike_type',
        ),
    ]
