# Generated by Django 3.2 on 2022-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_event_bike_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(
                default='https://velo-city-rc.s3.eu-west-1.amazonaws.com/media/bulls-road-bike.jpg',
                upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                default='https://velo-city-rc.s3.eu-west-1.amazonaws.com/media/bulls-road-bike.jpg',
                upload_to=''),
            preserve_default=False,
        ),
    ]
