# Generated by Django 3.2 on 2022-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='first_name', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='last_name', max_length=60),
            preserve_default=False,
        ),
    ]
