# Generated by Django 3.2 on 2022-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0002_auto_20220613_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2022-06-13'),
            preserve_default=False,
        ),
    ]
