# Generated by Django 3.2 on 2022-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0003_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_address',
            field=models.CharField(
                default='rocrill@email.com',
                max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(
                default='1111122',
                max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_type',
            field=models.CharField(
                choices=[
                    ('Hybrid',
                     'Hybrid'),
                    ('Road',
                     'Road'),
                    ('Mountain',
                     'Mountain'),
                    ('Vintage',
                     'Vintage')],
                default='Hybrid',
                max_length=15),
        ),
    ]
