# Generated by Django 3.2 on 2022-06-16 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0004_auto_20220614_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 16)),
        ),
    ]
