# Generated by Django 3.2 on 2022-06-19 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0006_auto_20220618_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 19)),
        ),
    ]
